core_admin:
    resource: "@AresCoreBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   adminold/

core_user:
    resource: "@AresCoreBundle/Controller/UserController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

core_chronometer:
    resource: "@AresCoreBundle/Controller/ChronometerController.php"
    type:     annotation
    prefix:   chronometer/
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin    
