<?php

namespace Ares\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    
    public function myFindUsersAssigned(){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ut.user')
            ->from('AresCoreBundle:usertask', 'ut')
            ->where("ut.designation = true")
            ->groupBy('ut.task')
        ;
        
        
     
        
        
        return $qb->getQuery()->getResult();        
    }    
}
