# Ares/CoreBundle/Resources/config/admin.yml
services:
    sonata.admin.task:
        class: Ares\CoreBundle\Admin\TaskAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Task" }
        arguments:
            - ~
            - Ares\CoreBundle\Entity\Task
            - ~
        calls:
            - [ setTranslationDomain, [AresCoreBundle]]